# Generated by Django 4.2.27 on 2026-01-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_alter_recipe_options_alter_recipe_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
